In [1]:
import pandas as pd 
import tensorflow as tf
import numpy as np 
import os 
import matplotlib.pyplot as plt
import keras 

In [2]:
# Upload google drive in our COLAB

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import cv2 
import glob as gb

In [4]:
trainpath = "/content/drive/MyDrive/Colab Notebooks/dataset/dataset03/Training"
testpath = "/content/drive/MyDrive/Colab Notebooks/dataset/dataset03/Testing"

In [5]:
code = {'glioma_tumor':0 ,'meningioma_tumor':1,'no_tumor':2 , "pituitary_tumor" :3}

def getcode(n) : 
    for x , y in code.items() : 
        if n == y : 
            return x  

In [6]:
from tensorflow.keras.preprocessing import image_dataset_from_directory

In [7]:
dataset_train = image_dataset_from_directory(trainpath, label_mode='categorical',image_size =(224, 224),batch_size=16 )
dataset_test = image_dataset_from_directory(testpath, label_mode='categorical' ,image_size =(224, 224),batch_size=16)

Found 2870 files belonging to 4 classes.
Found 394 files belonging to 4 classes.


In [8]:
dataset_test.class_names

['glioma_tumor', 'meningioma_tumor', 'no_tumor', 'pituitary_tumor']

In [9]:
from tensorflow.keras.applications import InceptionV3,VGG19,MobileNet

In [10]:
from tensorflow.keras.layers import Dense,Conv2D,Flatten

In [11]:
from tensorflow.keras import Model

In [ ]:
def create_model():
    print(1)
    inception = InceptionV3(include_top=True)
    output = Dense(4,activation='softmax')(inception.layers[-2].output)
    model = Model(inception.inputs,output)
    model.compile('adam','categorical_crossentropy','accuracy')
    for layer in model.layers[:-2]:
        layer.trainable = False
    return model

model = create_model()

1
96124928/96112376 [==============================] - 1s 0us/step


In [12]:
from tensorflow.keras.callbacks import TensorBoard

In [ ]:
tensorboard_callback = TensorBoard(histogram_freq=1,write_images=True)
h = model.fit(dataset_train,epochs=2,callbacks=[tensorboard_callback])

In [ ]:
model.save("brain-model1.h5")

In [ ]:
import tensorflow as tf 

In [ ]:
res = nmodule.predict(dataset_test)

In [ ]:
code = {'glioma_tumor':0, 'meningioma_tumor':1, 'no_tumor':2, 'pituitary_tumor':3}

In [ ]:
code.

dict_items([('glioma_tumor', 0), ('meningioma_tumor', 1), ('no_tumor', 2), ('pituitary_tumor', 3)])

In [ ]:
def getcode(n) :
  for x ,y in code.items() : 
    if n == y :
      return x 

In [ ]:
#getcode(np.argmax())

In [ ]:
test_path = "/content/drive/MyDrive/Colab Notebooks/dataset/new"

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
test_scal = ImageDataGenerator(rescale= 1./255,
                            shear_range = 0.2,
                            zoom_range = 0.2,
                            horizontal_flip = True,
)

test_val = test_scal.flow_from_directory(directory = test_path, target_size = (224,224))

Found 4 images belonging to 1 classes.


In [ ]:
predd = nmodule.predict(test_val)

In [ ]:
print(predd)

[[0.2689114  0.53450525 0.19596075 0.00062266]
 [0.26062083 0.53569317 0.20303208 0.00065394]
 [0.26357862 0.535177   0.20059337 0.00065098]
 [0.26489636 0.5351022  0.19935931 0.00064216]]


In [ ]:
arr = nmodule.predict(prepare(npath))

In [ ]:
print(arr[0][2]*100)

25.056686997413635


In [ ]:
def create_model():
    print(1)
    inception = MobileNet(include_top=True)
    output = Dense(4,activation='softmax')(inception.layers[-2].output)
    model = Model(inception.inputs,output)
    model.compile('adam','categorical_crossentropy','accuracy')
    for layer in model.layers[:-2]:
        layer.trainable = False
    return model

model2 = create_model()

1


In [ ]:
model2.compile(optimizer="Adam", loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

In [ ]:
h = model2.fit(dataset_train,epochs=2)

Epoch 1/2
180/180 [==============================] - 95s 522ms/step - loss: 0.6397 - accuracy: 0.7610
Epoch 2/2
180/180 [==============================] - 94s 522ms/step - loss: 0.5215 - accuracy: 0.8017


In [ ]:
model.save('brain-model2.h5')

In [ ]:
arr = model.predict(prepare(npath))